### ISSUE TITLE
Recommendation to make typography responsive?

### ISSUE THREAD

**Issue by nevvkid** [Pushplaybang/knife#15]
Hey! I am just trying knife the first time. 
Is there a way to change the size of the body font size you recommend?

```
h1,h2,h3,h4,h5,h6 {
  font-family: $heading-font-family;
}
h1 { @include ktype(5, 1, 1); }
h2 { @include ktype(4, 1, 1); }
h3 { @include ktype(3, 1, 1); }
h4 { @include ktype(2, 1, 1); }
h5 { @include ktype(1, 1, 0); }
h6 {
@include ktype(0, 1, 0);
    font-weight: normal;
    text-transform: capitalize;
}
p, ul, ol {
  @include ktype(0,0,1);
  @include media($large-screen) {
    @include ktype(1, 1, 0);
    line-height: 33px;
  }
}
```

This would work, not really...  

Thank you!
J

**Comment by Sntax** [comment]
Checkout https://github.com/Pushplaybang/knife#usage

You can set this in your basic variables.

**Comment by Pushplaybang** [comment]
@nevvkid beyond the $body-font-size var, remember that REMS are always relative the px size set on the HTML element, so simply adjusting that by a px up or down will adjust all sizes.

for maximum responsiveness set all your dimension values in either REMS or %.
